config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :search, only: [:index]
  resources :tiles, only: [:index]
  resources :finder, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/finder.rb
class Finder
  def self.all_words(tiles)
    self.verify_word_length(tiles).uniq
  end

  private

  def self.verify_word_length(tiles)
    self.anagramify(tiles).keep_if { |word| word.length > 1 }
  end

  def self.anagramify(tiles)
    self.make_list(tiles).map do |letters|
      response = AnagramicaService.get_words(letters.join(''))
      JSON.parse(response.body)["best"]
    end.flatten
  end

  def self.make_list(tiles)
    tiles_list = tiles.split('')
    tiles_combined = []
    i = 2
    while i <= tiles_list.length do
      tiles_combined << tiles_list.combination(i).to_a
      i += 1
    end
    tiles_combined.flatten(1).uniq
  end
end

app/models/search.rb
class Search
  def self.find_word(word)
    response = OedService.find_word(word)
    self.determine_response_status(response)
  end

  private

  def self.determine_response_status(response)
    if response.status == 404
      nil
    elsif response.status == 200
      res = JSON.parse(response.body)
      self.build_defs(res)
    end
  end

  def self.build_defs(res)
    self.parse_results(res).flatten.compact
  end

  def self.parse_results(res)
    res['results'].first['lexicalEntries'].map do |lex_entry|
      self.parse_entries(lex_entry)
    end
  end

  def self.parse_entries(lex_entry)
    lex_entry["entries"].map do |entry|
      self.find_defs(entry)
    end
  end

  def self.find_defs(entry)
    entry["senses"].map do |sense|
      sense["definitions"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @tiles = params["search"]
    @words = Finder.all_words(@tiles)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @word = params["search"]
    @definitions = Search.find_word(@word)
  end
end

app/controllers/tiles_controller.rb
class TilesController < ApplicationController
  def index

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/finder/index.html.erb
<div class="tiles-prompt">See All Available Words:</div>
<div class="tiles-form">
  <%= form_tag('/finder?tiles=', method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Submit' %>
  <% end %>
</div>


You can make <%= @words.length %> words from your tiles:

<ul>
  <% @words.each do |word| %>
    <li><%= word %></li>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "Word Searcher", root_path %></li>
    <li><%= link_to "Word Finder", tiles_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleChecker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<div class="search-prompt">Search for a word:</div>
<div class="search-form">
  <%= form_tag('/search?word=', method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Submit' %>
  <% end %>
</div>


<% if @definitions %>
  <h1><%= @word %> exists!</h1>

  <h3>Definitions: </h3>
  <ol>
    <% @definitions.each do |definition| %>
      <li><%= definition %></li>
    <% end %>
  </ol>
<% else %>
  <h1><%= @word %> does not exist.</h1>
<% end %>

app/views/tiles/index.html.erb
<div class="tiles-prompt">See All Available Words:</div>
<div class="tiles-form">
  <%= form_tag('/finder?tiles=', method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Submit' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="search-prompt">Search for a word:</div>
<div class="search-form">
  <%= form_tag('/search?word=', method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Submit' %>
  <% end %>
</div>